# Generated by Django 2.0.5 on 2018-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='乡镇')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('students', models.IntegerField(verbose_name='学生人数')),
                ('district', models.ForeignKey(on_delete=None, to='hele.District', verbose_name='所属乡镇')),
            ],
        ),
    ]
