# Generated by Django 2.0.5 on 2018-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hele', '0003_auto_20180901_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='geo_d',
            field=models.FloatField(verbose_name='维度'),
        ),
        migrations.AlterField(
            model_name='district',
            name='geo_l',
            field=models.FloatField(verbose_name='经度'),
        ),
    ]
