# Generated by Django 2.0.5 on 2018-09-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hele', '0004_auto_20180901_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Struct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学校名称')),
                ('rice', models.FloatField(verbose_name='大米')),
                ('ganhuo', models.FloatField(verbose_name='干货')),
                ('cake', models.FloatField(verbose_name='糕点')),
                ('egg', models.FloatField(verbose_name='蛋类')),
                ('chicken', models.FloatField(verbose_name='鸡鸭肉')),
                ('ricenoodle', models.FloatField(verbose_name='米粉')),
                ('milk', models.FloatField(verbose_name='奶制品')),
                ('beef', models.FloatField(verbose_name='牛肉')),
                ('oil', models.FloatField(verbose_name='食用油')),
                ('vegitable', models.FloatField(verbose_name='蔬菜')),
                ('flavor', models.FloatField(verbose_name='调味品')),
                ('pock', models.FloatField(verbose_name='猪肉')),
            ],
        ),
    ]
