# Generated by Django 2.0.5 on 2018-09-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hele', '0005_food_struct'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_struct',
            name='total',
            field=models.FloatField(default=1, verbose_name='总计'),
            preserve_default=False,
        ),
    ]
