# Generated by Django 2.0.5 on 2018-09-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hele', '0007_auto_20180902_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_struct',
            name='beef',
            field=models.FloatField(default=0, null=True, verbose_name='牛肉'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='cake',
            field=models.FloatField(default=0, null=True, verbose_name='糕点'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='chicken',
            field=models.FloatField(default=0, null=True, verbose_name='鸡鸭肉'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='egg',
            field=models.FloatField(default=0, null=True, verbose_name='蛋类'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='flavor',
            field=models.FloatField(default=0, null=True, verbose_name='调味品'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='ganhuo',
            field=models.FloatField(default=0, null=True, verbose_name='干货'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='milk',
            field=models.FloatField(default=0, null=True, verbose_name='奶制品'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='oil',
            field=models.FloatField(default=0, null=True, verbose_name='食用油'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='pock',
            field=models.FloatField(default=0, null=True, verbose_name='猪肉'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='rice',
            field=models.FloatField(default=0, null=True, verbose_name='大米'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='ricenoodle',
            field=models.FloatField(default=0, null=True, verbose_name='米粉'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='total',
            field=models.FloatField(default=0, null=True, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='food_struct',
            name='vegitable',
            field=models.FloatField(default=0, null=True, verbose_name='蔬菜'),
        ),
    ]
