# Generated by Django 2.0.5 on 2018-09-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hele', '0008_auto_20180902_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_struct',
            name='name',
            field=models.ForeignKey(null=True, on_delete=None, to='hele.School', verbose_name='学校名称'),
        ),
    ]
