# Generated by Django 2.0.5 on 2018-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hele', '0009_auto_20180902_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutri_of_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuqinyu', models.FloatField(null=True, verbose_name='畜禽鱼肉')),
                ('soilbean', models.FloatField(null=True, verbose_name='大豆坚果')),
                ('egg', models.FloatField(null=True, verbose_name='蛋类')),
                ('gushu', models.FloatField(null=True, verbose_name='谷薯类')),
                ('milk', models.FloatField(null=True, verbose_name='奶制品')),
                ('sault', models.FloatField(null=True, verbose_name='盐')),
                ('vigetable', models.FloatField(null=True, verbose_name='蔬菜类')),
                ('fruit', models.FloatField(null=True, verbose_name='水果类')),
                ('oil', models.FloatField(null=True, verbose_name='食用油')),
                ('total', models.FloatField(null=True, verbose_name='合计')),
                ('school', models.ForeignKey(null=True, on_delete=None, to='hele.School', verbose_name='学校名称')),
            ],
        ),
    ]
